name: Feature Request / 功能请求
description: Suggest a new feature or improvement
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.
        感谢您提出功能建议！请在下方描述您的想法。

  - type: textarea
    id: problem
    attributes:
      label: Problem / 问题描述
      description: Is your feature request related to a problem?
      placeholder: I would like to... / 我希望能够...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution / 建议的解决方案
      description: Describe the solution you'd like
      placeholder: I think we could add... / 我认为可以添加...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives / 替代方案
      description: Any alternative solutions or features you've considered
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Category / 类别
      options:
        - New Tool / 新工具
        - Desktop Environment / 桌面环境
        - Hardware Support / 硬件支持
        - Documentation / 文档
        - Build System / 构建系统
        - Other / 其他
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context / 额外信息
      description: Any other context or screenshots about the feature request
    validations:
      required: false
